### ISSUE TITLE
Using just with docker room - Network not found - or - ERR proxy error error="dial tcp: lookup 27e1e1175992 on 127.0.0.11:53: server misbehaving" module=proxy prefix=/test

### ISSUE THREAD

**Issue by cedricbieder** [m1k1o/neko-rooms#141]
Hi,

I want to use the neko-room with minimal settings, just the rooms without traefik or anything else. Is this possible?
If I try to set it up with your config:

```
version: "3.5"

networks:
  default:
    attachable: true
    name: "neko-rooms-net"

services:
  neko-rooms:
    image: "m1k1o/neko-rooms:latest"
    restart: "unless-stopped"
    environment:
      - "TZ=Europe/Vienna"
      - "NEKO_ROOMS_MUX=true"
      - "NEKO_ROOMS_EPR=59000-59049"
      - "NEKO_ROOMS_NAT1TO1=127.0.0.1" # IP address of your server that is reachable from client
      - "NEKO_ROOMS_INSTANCE_URL=http://127.0.0.1:8080/" # external URL
      - "NEKO_ROOMS_INSTANCE_NETWORK=neko-rooms-net"
      - "NEKO_ROOMS_TRAEFIK_ENABLED=false"
      - "NEKO_ROOMS_PATH_PREFIX=/room/"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

It will not create the `neko-rooms-net` network and run into in error if I start the room. 
If I created the network by hand, it creates the room, but I am not able to connect to it. 
I get the message: `neko-rooms-1  | 6:32PM ERR proxy error error="dial tcp: lookup 27e1e1175992 on 127.0.0.11:53: server misbehaving" module=proxy prefix=/test`.

Do I am missing a part here or it is not possible to run just the room without a traefik? 

Thank you for your work and help.

Best
