### ISSUE TITLE
Error response from daemon: invalid mount config for type "bind"

### ISSUE THREAD

**Issue by pbdco** [m1k1o/neko-rooms#143]
Hi @m1k1o , amazing project! Thanks for sharing

I'm having this issue when creating a firefox room with persistent data:

![image](https://github.com/user-attachments/assets/8153c911-e6e7-475e-8e15-4f969c63da42)

`neko-rooms-1  | 11:16PM ERR create: failed to create room error="Error response from daemon: invalid mount config for type \"bind\": bind source path does not exist: /opt/neko-rooms/data/rooms/gVVgYJBN/profile" module=api`

This is my docker-compose:

```
  neko-rooms:
    image: "m1k1o/neko-rooms:latest"
    restart: "unless-stopped"
    environment:
      - "TZ=Europe/Madrid"
      - "NEKO_ROOMS_MUX=true"
      - "NEKO_ROOMS_EPR=59000-59049"
      - "NEKO_ROOMS_NAT1TO1=192.168.1.222" # IP address of your server that is reachable from client
      - "NEKO_ROOMS_INSTANCE_URL=http://192.168.1.222:8280/" # external URL
      - "NEKO_ROOMS_INSTANCE_NETWORK=neko-rooms-net"
      - "NEKO_ROOMS_TRAEFIK_ENABLED=false"
      - "NEKO_ROOMS_PATH_PREFIX=/room/"
      - "NEKO_ROOMS_STORAGE_ENABLED=true"    # Enable storage https://github.com/m1k1o/neko-rooms/blob/master/docs/storage.md
      - "NEKO_ROOMS_STORAGE_INTERNAL=/data"   # Container storage path
      - "NEKO_ROOMS_STORAGE_EXTERNAL=/opt/neko-rooms/data"    # Host storage path
    ports:
      - "8280:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./neko-rooms/data:/data"
      - "./neko-rooms/rooms:/opt/neko-rooms/data/rooms"  # Required? 🤔
    networks:
      - neko-rooms-net

networks:
  neko-rooms-net:
    external: true
``` 

What I'm missing?
Thanks!

**Comment by m1k1o** [comment]
The external path is the path outside of the docker container so you should not bind it to it (second volume). And unless your docker-compose file is in `/opt/` then its incorrect path. It needs to be the `./neko-rooms/data` path, but absolute.

**Comment by pbdco** [comment]
Got it! Now I can create rooms with persistent data enabled, but I'm still unable to figure out how to persist files such as downloads from Firefox. Currently if I download a file, I don't see it anywhere in the /neko-rooms/data folder. What's the issue here?

Thanks @m1k1o 

```
  neko-rooms:
    image: "m1k1o/neko-rooms:latest"
    restart: "unless-stopped"
    environment:
      - "TZ=Europe/Madrid"
      - "NEKO_ROOMS_MUX=true"
      - "NEKO_ROOMS_EPR=59000-59049"
      - "NEKO_ROOMS_NAT1TO1=192.168.1.222" # IP address of your server that is reachable from client
      - "NEKO_ROOMS_INSTANCE_URL=http://neko.debian/" # external URL
      - "NEKO_ROOMS_INSTANCE_NETWORK=neko-rooms-net"
      - "NEKO_ROOMS_TRAEFIK_ENABLED=false"
      - "NEKO_ROOMS_PATH_PREFIX=/room/"
      - "NEKO_ROOMS_STORAGE_ENABLED=true"    # Enable storage https://github.com/m1k1o/neko-rooms/blob/master/docs/storage.md
      - "NEKO_ROOMS_STORAGE_INTERNAL=/data"   # Container storage path
      - "NEKO_ROOMS_STORAGE_EXTERNAL=/home/p/DOCKER/WEBRTC/neko/neko-rooms/data"    # Host storage path
    ports:
      - "8280:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./neko-rooms/data:/data"
    networks:
      - neko-rooms-net

networks:
  neko-rooms-net:
    external: true
```
