### ISSUE TITLE
Using neko-rooms with nginx

### ISSUE THREAD

**Issue by mwllgr** [m1k1o/neko-rooms#3]
Hello, how can I use this project with nginx?
I'm using the neko reverse proxy configuration, however, with neko-rooms I only get a 404 not found.

I started the server using the .http.yml file.

**Comment by m1k1o** [comment]
Hello,

traefik still needs to be running to forward traffic to rooms. You can put nginx behind that, but not replace that. Your domain name specified for traefik has to match your proxy's output domain. Currently, there is no support for custom paths (so you cannot host your neko-rooms on `example.com/neko-rooms/` but it needs own subdomain e.g. `neko-rooms.example.com`).

**Comment by m1k1o** [comment]
Example working configuration. Internal domain name is only `traefik`, what is also name of the service.

```yaml
version: "3.7"

networks:
  default:
    attachable: "true"
    name: "neko-rooms-traefik"

services:
  traefik:
    image: "traefik:2.4"
    restart: "unless-stopped"
    environment:
      - "TZ=Europe/Vienna"
    command:
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=neko-rooms-traefik"
      - "--entrypoints.web.address=:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  neko-rooms:
    image: "m1k1o/neko-rooms:latest"
    restart: "unless-stopped"
    environment:
      - "TZ=Europe/Vienna"
      - "NEKO_ROOMS_EPR=59000-59049"
      - "NEKO_ROOMS_NAT1TO1=10.8.0.1" # IP address of your server
      - "NEKO_ROOMS_TRAEFIK_DOMAIN=traefik" # traefik domain (name of the service)
      - "NEKO_ROOMS_TRAEFIK_ENTRYPOINT=web"
      - "NEKO_ROOMS_TRAEFIK_NETWORK=neko-rooms-traefik"
      - "NEKO_ROOMS_TRAEFIK_PORT=8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.neko-rooms-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.neko-rooms.entrypoints=web"
      - "traefik.http.routers.neko-rooms.rule=Host(`traefik`)" # traefik domain (name of the service)

  #
  # This should be replaced by your own existing nginx instance
  #

  nginx:
    image: "nginx"
    restart: "unless-stopped"
    environment:
      - "TZ=Europe/Vienna"
    ports:
      - "8080:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
```

Nginx config:

```conf
server {
    listen 80;

    location / {
        proxy_pass http://traefik:8080; # traefik domain (name of the service)
    }
}
```
